### ISSUE TITLE
fix compass import

### ISSUE THREAD

**Issue by jedwards1211** [wallscavesurvey/walls#2]
Right now compass import isn't working, because I don't have the `wallcss` project in this repo.  I was having a bunch of compile issues with it, so I thought maybe it was incomplete.

**Comment by amlynarczyk** [comment]
Is there a Chance, that you will share missing project somewhere, to let me try figuring out, what's wrong?

**Comment by jedwards1211** [comment]
@amlynarczyk I was wrong, it is in this repo at https://github.com/wallscavesurvey/walls/blob/master/trx/Walls32/wallcss

**Comment by jedwards1211** [comment]
I think you'll have to add it back to the set of projects for Visual Studio to build though
